/* SPDX-License-Identifier: GPL-2.0 */
#ifndef VM_EVENT_ITEM_H_INCLUDED
#define VM_EVENT_ITEM_H_INCLUDED

#include <linux/thread_info.h>

#ifdef CONFIG_ZONE_DMA
#define DMA_ZONE(xx) xx##_DMA,
#else
#define DMA_ZONE(xx)
#endif

#ifdef CONFIG_ZONE_DMA32
#define DMA32_ZONE(xx) xx##_DMA32,
#else
#define DMA32_ZONE(xx)
#endif

#ifdef CONFIG_HIGHMEM
#define HIGHMEM_ZONE(xx) xx##_HIGH,
#else
#define HIGHMEM_ZONE(xx)
#endif

#ifdef CONFIG_ZONE_DEVICE
#define DEVICE_ZONE(xx) xx##_DEVICE,
#else
#define DEVICE_ZONE(xx)
#endif

#define FOR_ALL_ZONES(xx) DMA_ZONE(xx) DMA32_ZONE(xx) xx##_NORMAL, \
	HIGHMEM_ZONE(xx) xx##_MOVABLE, DEVICE_ZONE(xx)

enum vm_event_item { PGPGIN, PGPGOUT, PSWPIN, PSWPOUT,
		FOR_ALL_ZONES(PGALLOC)
		FOR_ALL_ZONES(ALLOCSTALL)
		FOR_ALL_ZONES(PGSCAN_SKIP)
		PGFREE, PGACTIVATE, PGDEACTIVATE, PGLAZYFREE,
		PGFAULT, PGMAJFAULT,
		PGLAZYFREED,
		PGREFILL,
		PGREUSE,
		PGSTEAL_KSWAPD,
		PGSTEAL_DIRECT,
		PGSTEAL_KHUGEPAGED,
		PGSTEAL_PROACTIVE,
		PGSCAN_KSWAPD,
		PGSCAN_DIRECT,
		PGSCAN_KHUGEPAGED,
		PGSCAN_PROACTIVE,
		PGSCAN_DIRECT_THROTTLE,
		PGSCAN_ANON,
		PGSCAN_FILE,
		PGSTEAL_ANON,
		PGSTEAL_FILE,
#ifdef CONFIG_NUMA
		PGSCAN_ZONE_RECLAIM_SUCCESS,
		PGSCAN_ZONE_RECLAIM_FAILED,
#endif
		PGINODESTEAL, SLABS_SCANNED, KSWAPD_INODESTEAL,
		KSWAPD_LOW_WMARK_HIT_QUICKLY, KSWAPD_HIGH_WMARK_HIT_QUICKLY,
		PAGEOUTRUN, PGROTATED,
		DROP_PAGECACHE, DROP_SLAB,
		OOM_KILL,
#ifdef CONFIG_NUMA_BALANCING
		NUMA_PTE_UPDATES,
		NUMA_HUGE_PTE_UPDATES,
		NUMA_HINT_FAULTS,
		NUMA_HINT_FAULTS_LOCAL,
		NUMA_PAGE_MIGRATE,
#endif
#ifdef CONFIG_MIGRATION
		PGMIGRATE_SUCCESS, PGMIGRATE_FAIL,
		THP_MIGRATION_SUCCESS,
		THP_MIGRATION_FAIL,
		THP_MIGRATION_SPLIT,
#endif
#ifdef CONFIG_COMPACTION
		COMPACTMIGRATE_SCANNED, COMPACTFREE_SCANNED,
		COMPACTISOLATED,
		COMPACTSTALL, COMPACTFAIL, COMPACTSUCCESS,
		KCOMPACTD_WAKE,
		KCOMPACTD_MIGRATE_SCANNED, KCOMPACTD_FREE_SCANNED,
		KCOMPACTD_ORDER2_CREATED,
#endif
		ALLOC_SUCCESS_ORDER0,
		ALLOC_SUCCESS_ORDER2,
		ALLOC_FAIL_WMARK,
		ALLOC_FAIL_FRAGMENT,
		ALLOC_STALL_WMARK,
		ALLOC_STALL_FRAGMENT,
		KCOMPACTD_TIMEOUT_WAKE,
		KCOMPACTD_WAKE_REQUEST,
		KCOMPACTD_WOKE_BY_ALLOC,
		KCOMPACTD_WOKE_BY_VMSCAN,
		KCOMPACTD_ORDER2_LOW,
		KCOMPACTD_O2_MOVABLE_EMPTY,
		KCOMPACTD_O2_MOVABLE_HAS,
		KCOMPACTD_WAKE_VMSCAN,
		KCOMPACTD_WAKE_ALLOC_SLOWPATH,
#ifdef CONFIG_HUGETLB_PAGE
		HTLB_BUDDY_PGALLOC, HTLB_BUDDY_PGALLOC_FAIL,
#endif
#ifdef CONFIG_CMA
		CMA_ALLOC_SUCCESS,
		CMA_ALLOC_FAIL,
#endif
		UNEVICTABLE_PGCULLED,	/* culled to noreclaim list */
		UNEVICTABLE_PGSCANNED,	/* scanned for reclaimability */
		UNEVICTABLE_PGRESCUED,	/* rescued from noreclaim list */
		UNEVICTABLE_PGMLOCKED,
		UNEVICTABLE_PGMUNLOCKED,
		UNEVICTABLE_PGCLEARED,	/* on COW, page truncate */
		UNEVICTABLE_PGSTRANDED,	/* unable to isolate on unlock */
#ifdef CONFIG_TRANSPARENT_HUGEPAGE
		THP_FAULT_ALLOC,
		THP_FAULT_FALLBACK,
		THP_FAULT_FALLBACK_CHARGE,
		THP_COLLAPSE_ALLOC,
		THP_COLLAPSE_ALLOC_FAILED,
		THP_FILE_ALLOC,
		THP_FILE_FALLBACK,
		THP_FILE_FALLBACK_CHARGE,
		THP_FILE_MAPPED,
		THP_SPLIT_PAGE,
		THP_SPLIT_PAGE_FAILED,
		THP_DEFERRED_SPLIT_PAGE,
		THP_UNDERUSED_SPLIT_PAGE,
		THP_SPLIT_PMD,
		THP_SCAN_EXCEED_NONE_PTE,
		THP_SCAN_EXCEED_SWAP_PTE,
		THP_SCAN_EXCEED_SHARED_PTE,
#ifdef CONFIG_HAVE_ARCH_TRANSPARENT_HUGEPAGE_PUD
		THP_SPLIT_PUD,
#endif
		THP_ZERO_PAGE_ALLOC,
		THP_ZERO_PAGE_ALLOC_FAILED,
		THP_SWPOUT,
		THP_SWPOUT_FALLBACK,
		ANON_MTHP_VMA_UNSUITABLE_ORDER2,
		COW_MTHP_ORDER2,
		COW_MTHP_FALLBACK_ORDER0,
		COW_MTHP_VMA_UNSUITABLE_ORDER2,
		ALLOC_FAIL_WMARK_ANON,
		ALLOC_FAIL_WMARK_FILE,
		ALLOC_FAIL_FRAGMENT_ANON,
		ALLOC_FAIL_FRAGMENT_FILE,
		ALLOC_STALL_WMARK_ANON,
		ALLOC_STALL_WMARK_FILE,
		ALLOC_STALL_FRAGMENT_ANON,
		ALLOC_STALL_FRAGMENT_FILE,
		VMA_ANON_ALLOC_ORDER0_TOTAL,
		VMA_ANON_ALLOC_ORDER2_TOTAL,
		VMA_ANON_ALLOC_ORDER0_ANON_FAULT,
		VMA_ANON_ALLOC_ORDER2_ANON_FAULT,
		VMA_ANON_ALLOC_ORDER0_SWAPIN,
		VMA_ANON_ALLOC_ORDER2_SWAPIN,
		VMA_ANON_ALLOC_ORDER0_COW,
		VMA_ANON_ALLOC_ORDER2_COW,
		VMA_ANON_ALLOC_ORDER0_FILE_COW,
		VMA_ANON_ALLOC_ORDER2_FILE_COW,
		VMA_ANON_ALLOC_ORDER0_UFFD_COPY,
		VMA_ANON_ALLOC_ORDER2_UFFD_COPY,
		VMA_ANON_ALLOC_ORDER0_UFFD_ZEROPAGE,
		VMA_ANON_ALLOC_ORDER2_UFFD_ZEROPAGE,
		VMA_ANON_ALLOC_ORDER0_CLASS_DALVIK,
		VMA_ANON_ALLOC_ORDER2_CLASS_DALVIK,
		VMA_ANON_ALLOC_ORDER0_CLASS_SCUDO,
		VMA_ANON_ALLOC_ORDER2_CLASS_SCUDO,
		VMA_ANON_ALLOC_ORDER0_CLASS_BIONIC,
		VMA_ANON_ALLOC_ORDER2_CLASS_BIONIC,
		VMA_ANON_ALLOC_ORDER0_CLASS_MTHP_VMA,
		VMA_ANON_ALLOC_ORDER2_CLASS_MTHP_VMA,
		VMA_ANON_ALLOC_ORDER0_CLASS_STACK,
		VMA_ANON_ALLOC_ORDER2_CLASS_STACK,
		VMA_ANON_ALLOC_ORDER0_CLASS_FILE_PRIVATE,
		VMA_ANON_ALLOC_ORDER2_CLASS_FILE_PRIVATE,
		VMA_ANON_ALLOC_ORDER0_CLASS_OTHER,
		VMA_ANON_ALLOC_ORDER2_CLASS_OTHER,
		FILE_ALLOC_ORDER0_TOTAL,
		FILE_ALLOC_ORDER2_TOTAL,
		FILE_ALLOC_ORDER0_UNKNOWN,
		FILE_ALLOC_ORDER2_UNKNOWN,
		FILE_ALLOC_ORDER0_READAHEAD,
		FILE_ALLOC_ORDER2_READAHEAD,
		FILE_ALLOC_ORDER0_GETFOLIO_MMAP,
		FILE_ALLOC_ORDER2_GETFOLIO_MMAP,
		FILE_ALLOC_ORDER0_GETFOLIO_WRITE,
		FILE_ALLOC_ORDER2_GETFOLIO_WRITE,
		FILE_ALLOC_ORDER0_GETFOLIO_OTHER,
		FILE_ALLOC_ORDER2_GETFOLIO_OTHER,
		FILE_ALLOC_ORDER0_BUFFERED_READ,
		FILE_ALLOC_ORDER2_BUFFERED_READ,
		FILE_ALLOC_ORDER0_READ_CACHE,
		FILE_ALLOC_ORDER2_READ_CACHE,
		UFFD_MFILL_ORDER2_ATTEMPT_COPY,
		UFFD_MFILL_ORDER2_ATTEMPT_ZEROPAGE,
		UFFD_MFILL_ORDER2_SUCCESS_COPY,
		UFFD_MFILL_ORDER2_SUCCESS_ZEROPAGE,
			UFFD_MFILL_ORDER0_SUCCESS_COPY,
			UFFD_MFILL_ORDER0_SUCCESS_ZEROPAGE,
			ORDER0_BINDER_BUFFER_PAGE,
			ORDER0_TLB_GATHER_BATCH_PAGE,
			ORDER0_TLB_TABLE_BATCH_PAGE,
			ORDER0_PTE_ALLOC_PAGE,
			ORDER0_PMD_ALLOC_PAGE,
			ORDER0_VMALLOC_PAGE,
			ORDER0_SLUB_NEW_SLAB_PAGE,
			ORDER0_ZSMALLOC_PAGE,
			ORDER2_ZSMALLOC_PAGE,
			DMABUF_ALLOC_ORDER0,
			FORK_DUP_TASK_STRUCT_EVENT,
			FORK_VMAP_STACK_PAGES_EXPECTED,
			FORK_NONVMAP_STACK_ORDER_PAGES,
			SCUDO_VMA_UNSUITABLE_ORDER2,
			DALVIK_VMA_UNSUITABLE_ORDER2,
			SCUDO_PTE_OCCUPIED_ORDER2,
			DALVIK_PTE_OCCUPIED_ORDER2,
			BIONIC_VMA_UNSUITABLE_ORDER2,
		MTHP_VMA_UNSUITABLE_ORDER2,
			STACK_VMA_UNSUITABLE_ORDER2,
			OTHER_VMA_UNSUITABLE_ORDER2,
			BIONIC_PTE_OCCUPIED_ORDER2,
		MTHP_VMA_PTE_OCCUPIED_ORDER2,
			STACK_PTE_OCCUPIED_ORDER2,
			OTHER_PTE_OCCUPIED_ORDER2,
			ANON_MTHP_ORDER2_VMA_LEFT_BOUNDARY,
			ANON_MTHP_ORDER2_VMA_RIGHT_BOUNDARY,
			ANON_MTHP_ORDER2_VMA_TOO_SMALL,
			ANON_MTHP_ORDER2_NOT_ALLOWED_DALVIK,
			ANON_MTHP_ORDER2_NOT_ALLOWED_SCUDO,
			ANON_MTHP_ORDER2_NOT_ALLOWED_BIONIC,
		ANON_MTHP_ORDER2_NOT_ALLOWED_MTHP_VMA,
			ANON_MTHP_ORDER2_NOT_ALLOWED_STACK,
			ANON_MTHP_ORDER2_NOT_ALLOWED_OTHER,
			ANON_FAULT_ORDER0_CLASS_DALVIK,
			ANON_FAULT_ORDER0_CLASS_SCUDO,
			ANON_FAULT_ORDER0_CLASS_BIONIC,
		ANON_FAULT_ORDER0_CLASS_MTHP_VMA,
			ANON_FAULT_ORDER0_CLASS_STACK,
			ANON_FAULT_ORDER0_CLASS_OTHER,
			ANON_MTHP_ORDER2_UFFD_ARMED,
			ANON_MTHP_ORDER2_VMA_NOT_ALLOWED,
			ANON_MTHP_ORDER2_VMA_SUITABLE_FILTERED,
			ANON_MTHP_ORDER2_PTE_RANGE_NOT_EMPTY,
			ANON_MTHP_ORDER2_ALLOC_FAIL,
			ANON_MTHP_ORDER2_MEMCG_FAIL,
			COW_MTHP_ORDER2_FALLBACK_OLD_FOLIO_NOT_ORDER2,
			COW_MTHP_ORDER2_FALLBACK_VMA_NOT_ALLOWED,
			COW_MTHP_ORDER2_FALLBACK_ALLOC_FAIL,
			COW_MTHP_ORDER2_FALLBACK_PTE_CHANGED_OR_UNUSABLE,
	#endif
#ifdef CONFIG_MEMORY_BALLOON
		BALLOON_INFLATE,
		BALLOON_DEFLATE,
#ifdef CONFIG_BALLOON_COMPACTION
		BALLOON_MIGRATE,
#endif
#endif
#ifdef CONFIG_DEBUG_TLBFLUSH
		NR_TLB_REMOTE_FLUSH,	/* cpu tried to flush others' tlbs */
		NR_TLB_REMOTE_FLUSH_RECEIVED,/* cpu received ipi for flush */
		NR_TLB_LOCAL_FLUSH_ALL,
		NR_TLB_LOCAL_FLUSH_ONE,
#endif /* CONFIG_DEBUG_TLBFLUSH */
#ifdef CONFIG_SWAP
		SWAP_RA,
		SWAP_RA_HIT,
		SWPIN_ZERO,
		SWPOUT_ZERO,
#ifdef CONFIG_KSM
		KSM_SWPIN_COPY,
#endif
#endif
#ifdef CONFIG_KSM
		COW_KSM,
#endif
#ifdef CONFIG_ZSWAP
		ZSWPIN,
		ZSWPOUT,
		ZSWPWB,
#endif
#ifdef CONFIG_X86
		DIRECT_MAP_LEVEL2_SPLIT,
		DIRECT_MAP_LEVEL3_SPLIT,
		DIRECT_MAP_LEVEL2_COLLAPSE,
		DIRECT_MAP_LEVEL3_COLLAPSE,
#endif
#ifdef CONFIG_PER_VMA_LOCK_STATS
		VMA_LOCK_SUCCESS,
		VMA_LOCK_ABORT,
		VMA_LOCK_RETRY,
		VMA_LOCK_MISS,
#endif
#ifdef CONFIG_DEBUG_STACK_USAGE
		KSTACK_1K,
#if THREAD_SIZE > 1024
		KSTACK_2K,
#endif
#if THREAD_SIZE > 2048
		KSTACK_4K,
#endif
#if THREAD_SIZE > 4096
		KSTACK_8K,
#endif
#if THREAD_SIZE > 8192
		KSTACK_16K,
#endif
#if THREAD_SIZE > 16384
		KSTACK_32K,
#endif
#if THREAD_SIZE > 32768
		KSTACK_64K,
#endif
#if THREAD_SIZE > 65536
		KSTACK_REST,
#endif
#endif /* CONFIG_DEBUG_STACK_USAGE */
		NR_VM_EVENT_ITEMS
};

#ifndef CONFIG_TRANSPARENT_HUGEPAGE
#define THP_FILE_ALLOC ({ BUILD_BUG(); 0; })
#define THP_FILE_FALLBACK ({ BUILD_BUG(); 0; })
#define THP_FILE_FALLBACK_CHARGE ({ BUILD_BUG(); 0; })
#define THP_FILE_MAPPED ({ BUILD_BUG(); 0; })
#endif

#endif		/* VM_EVENT_ITEM_H_INCLUDED */
